ToDo/Models/ErrorViewModel.cs
namespace ToDo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDo/Models/ToDoTasks.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ToDo.Models
{
    public class ToDoTasks
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Title { get; set; }
                //[Display(Name ="helloworld")]  It is  possible to change name in add a task
                //more info https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations?view=net-6.0
        [Required]
        public string Details { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public DateTime ComplitedDate { get; set; } = default(DateTime);
    }
}

ToDo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDo.Models;

namespace ToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDo/Controllers/ToDoListController.cs
using Microsoft.AspNetCore.Mvc;
using ToDo.Data;
using ToDo.Models;

namespace ToDo.Controllers
{
    public class ToDoListController : Controller
    {
        private readonly ToDoDBContext _db;

        public string searchtext { get; set; }

        public ToDoListController(ToDoDBContext? DB)
        {
            _db = DB;
        }



        public IActionResult Test(dynamic search)
        {
           
            return View();
        }
        
        public IActionResult Index()
        {
            IEnumerable<ToDoTasks> objToDoList = _db.ToDoTasks;
            return View(objToDoList);
        }     
        
        //Get
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ToDoTasks obj)
        {
            if (ModelState.IsValid)
            {
            _db.ToDoTasks.Add(obj);
            _db.SaveChanges();
            TempData["success"] = "Task added successfully";
            return RedirectToAction("Index");
            }
            return View(obj);

            
        }


        public IActionResult Edit(int ? id)
        {
            if (id == null || id == 0) { return NotFound(); };

            var GetTaskfromDB = _db.ToDoTasks.Find(id);

            if (GetTaskfromDB == null) { return NotFound(); };
            return View(GetTaskfromDB);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ToDoTasks obj)
        {
            if (ModelState.IsValid)
            {
                _db.ToDoTasks.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Task updated successfully";
                return RedirectToAction("Index");
            }


            return View(obj);


        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0) { return NotFound(); };

            var GetTaskfromDB = _db.ToDoTasks.Find(id);

            if (GetTaskfromDB == null) { return NotFound(); };
            _db.ToDoTasks.Remove(GetTaskfromDB);
            _db.SaveChanges();
            TempData["success"] = "Task removed successfully";
            return RedirectToAction("Index");
        }

        public IActionResult Done(int? id)
        {
             if (id == null || id == 0) { return NotFound(); };
            var GetTaskfromDB = _db.ToDoTasks.Find(id);

            if (GetTaskfromDB == null) { return NotFound(); };
            GetTaskfromDB.ComplitedDate = DateTime.Now;
            _db.ToDoTasks.Update(GetTaskfromDB);
            _db.SaveChanges();
            TempData["success"] = "Task done successfully";
            return RedirectToAction("Index");

        } 
        
        public IActionResult Undone(int? id)
        {
             if (id == null || id == 0) { return NotFound(); };
            var GetTaskfromDB = _db.ToDoTasks.Find(id);

            if (GetTaskfromDB == null) { return NotFound(); };
            GetTaskfromDB.ComplitedDate = default(DateTime);
            _db.ToDoTasks.Update(GetTaskfromDB);
            _db.SaveChanges();
            TempData["success"] = "Task undone successfully";
            return RedirectToAction("Index");

        }


    }
}

ToDo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo</title>
    <link rel="stylesheet" href="~/css/Bootswatch.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="#">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="ToDoList" asp-action="index">ToDo List</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="ToDoList" asp-action="edit">edit</a>
        </li>
      </ul>

    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2021 - ToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDo/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
    
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
  
    
}

ToDo/Views/ToDoList/Create.cshtml
@model ToDoTasks
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="Text-primary">Add Task</h2>
        <hr />
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Details"></label>
            <input asp-for="Details" class="form-control"/>
            <span asp-validation-for="Details" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Add</button>
       
        <a asp-controller="ToDoList" asp-action="Index" class="btn btn-secondary" style="width:150px">Go Back</a>
    </div>

</form>

@*This one will stop re-lode when validation fails*@
@*Partial view means add one view in another view*@
@section Scripts{
    @{
        <partial Name="_ValidationScriptsPartial"></partial>
    }
}

ToDo/Views/ToDoList/Edit.cshtml
@model ToDoTasks
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="Text-primary">Edit Task</h2>
        <hr />
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Details"></label>
            <input asp-for="Details" class="form-control"/>
            <span asp-validation-for="Details" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
       
        <a asp-controller="ToDoList" asp-action="Index" class="btn btn-secondary" style="width:150px">Go Back</a>
    </div>

</form>

@*This one will stop re-lode when validation fails*@
@*Partial view means add one view in another view*@
@section Scripts{
    @{
        <partial Name="_ValidationScriptsPartial"></partial>
    }
}

ToDo/Views/ToDoList/Index.cshtml
@model IEnumerable<ToDoTasks>


@{
    ViewData["Title"] = "Index";
}



<div class="container p-3">
    <div class="row pt-4">
        <div style="margin:30px 0px">
           
         <form class="d-flex" style="width:100%">
        <input class="form-control me-sm-2" type="text" placeholder="Search" style="text-align:center">
        <button class="btn btn-secondary my-2 my-sm-0" style="width:10%" asp-action="Test">Search</button>
      </form>
       
        </div>
        <div class="col-6">
            <h2 class="text-primary">
                ToDo - List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ToDoList"
               asp-action="Create"
            class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>&nbsp; Add a task
            </a>

        </div>

    </div>

</div>
<br />


@{
    bool existin = Model.Any(e => Equals(e.ComplitedDate, default(DateTime)));
}

@if (existin)
{



<table class="table table-bordered table-striped" style="width:100%"  >
    <thead>
        <tr class="table-primary">
            <th style="text-align: center">
                Title
            </th>
            <th style="text-align: center">
                Details
            </th>
            <th style="text-align: center">
                Created Date
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>


    </thead>
    <tbody>

        @foreach(var obj in Model)
        {
         
            if (Equals(obj.ComplitedDate, default(DateTime)))
            {
                
               
               <tr>
                <td width="20%" style="text-align: center; vertical-align: middle; ">
                    @obj.Title
                </td>
                <td width="60%" style="text-align: center; vertical-align: middle;">
                    @obj.Details
                </td>
                <td width="20%" style="text-align: center; vertical-align: middle;">
                    @obj.CreatedDate.ToShortDateString()
                </td>
                <td>
                    <div c1ass="w-75 btn-group" role="group">
                        <a asp-controller="ToDoList" asp-action="Done" asp-route-id="@obj.ID" class="btn btn-success mx-1"><i class="bi bi-check-circle"></i>Done</a>

                    </div>
                </td>                <td>
                    <div c1ass="w-75 btn-group" role="group">
                        <a asp-controller="ToDoList" asp-action="Edit" asp-route-id="@obj.ID" class="btn btn-primary mx-1"><i class="bi bi-pen-fill"></i>Edit</a>

                    </div>
                </td>
                   <td>
                    <div c1ass="w-75 btn-group" role="group">
                        <a asp-controller="ToDoList" asp-action="Delete" asp-route-id="@obj.ID" class="btn btn-danger mx-1"><i class="bi bi-trash"></i>Delete</a>

                    </div>
                </td>
                </tr>

            }

        }    
    </tbody>

</table>
}

@{
    bool exist = Model.Any(e => !Equals(e.ComplitedDate, default(DateTime)));
}

@if (exist)
{
    <div class="col-6">
            <h2 class="text-primary">
                ToDo - Done List 
            </h2>
        </div>
    <table class="table table-striped" style="width:100%"  >
    <thead>
        <tr class="table-primary">
            <th style="text-align: center">
                Title
            </th>
            <th style="text-align: center">
                Details
            </th>
            <th style="text-align: center">
                Created Date
            </th>
            <th style="text-align: center">
                Completed Date
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>


    </thead>
    <tbody>

        @foreach(var obj in Model)
        {
         
            if (!Equals(obj.ComplitedDate, default(DateTime)))
            {
                
               
               <tr>
                <td width="20%" style="text-align: center; vertical-align: middle; text-decoration: line-through;">
                    @obj.Title
                </td> 
                <td width="40%" style="text-align: center; vertical-align: middle; text-decoration: line-through;">
                    @obj.Details
                </td>
                <td width="20%" style="text-align: center; vertical-align: middle; text-decoration: line-through;">
                    @obj.CreatedDate.ToShortDateString()
                </td>
                <td width="30%" style="text-align: center; vertical-align: middle; text-decoration: line-through;">
                    @obj.ComplitedDate.ToShortDateString()
                </td>
                <td>
                    <div c1ass="w-65 btn-group" role="group">
                        <a asp-controller="ToDoList" asp-action="Undone" asp-route-id="@obj.ID" class="btn btn-success mx-1"><i class="bi bi-arrow-clockwise"></i>Undone</a>

                    </div>
                </td>
                   <td>
                    <div c1ass="w-75 btn-group" role="group">
                        <a asp-controller="ToDoList" asp-action="Delete" asp-route-id="@obj.ID" class="btn btn-danger mx-1"><i class="bi bi-trash"></i>Delete</a>

                    </div>
                </td>
                </tr>

            }

        }    
    </tbody>

</table>
    
}